server:
  port: 8081
  servlet.context-path: /vaccination

spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/vaccination
    username: konstantin
    password: konstantin

  flyway:
    baseline-on-migrate: true
  jpa:
    open-in-view: false

#logging:
#  config: classpath:log4j2.xml