server:
  port: 8080
  servlet.context-path: /vaccination/vaccination_service

spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:6433/service_db
    username: konstantin
    password: konstantin

  liquibase:
    enabled: true
    change-log: classpath:/db/changelog/db.changelog-master.xml