server:
  port: 8081
  servlet.context-path: /vaccination/person_service

spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/vaccination
    username: konstantin
    password: konstantin

  liquibase:
    enabled: true
    change-log: classpath:/db/changelog/db.changelog-master.xml
